version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: iqa3-postgres
    restart: always
    environment:
      POSTGRES_DB: iqa3
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./Backend
    container_name: iqa3-backend
    depends_on:
      - postgres
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/iqa3
    volumes:
      - ./Backend:/app
      - /app/node_modules

  frontend:
    build: ./Frontend
    container_name: iqa3-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    volumes:
     - ./Frontend/my-app/src:/app/src          
     - ./Frontend/my-app/public:/app/public    

volumes:
  postgres_data: