import { Injectable, Logger, HttpException, HttpStatus } from "@nestjs/common";
import { ConfigService } from "@nestjs/config";

@Injectable()
export class RecaptchaService {
  private readonly logger = new Logger(RecaptchaService.name);
  private static readonly VERIFY_TIMEOUT_MS = 8000;

  // Standard reCAPTCHA v2/v3 secret keys (one per platform)
  private readonly secrets: string[];

  // reCAPTCHA Enterprise config (shared across Enterprise platforms)
  private readonly enterpriseApiKey: string | undefined;
  private readonly enterpriseProjectId: string | undefined;
  // Site keys per platform — add more here as new platforms join
  private readonly enterpriseSiteKeys: string[];

  constructor(private readonly configService: ConfigService) {
    this.secrets = [
      this.configService.get<string>("security.recaptchaSecret"),
    ].filter((s): s is string => Boolean(s));

    this.enterpriseApiKey = this.configService.get<string>("security.recaptchaEnterpriseApiKey");
    this.enterpriseProjectId = this.configService.get<string>("security.recaptchaEnterpriseProjectId");
    this.enterpriseSiteKeys = [
      this.configService.get<string>("security.recaptchaEnterpriseAndroidSiteKey"),
      this.configService.get<string>("security.recaptchaEnterpriseWebSiteKey"),
    ].filter((k): k is string => Boolean(k));
  }

  private get hasAnyConfig(): boolean {
    return (
      this.secrets.length > 0 ||
      Boolean(this.enterpriseApiKey && this.enterpriseProjectId && this.enterpriseSiteKeys.length > 0)
    );
  }

  // Verify a reCAPTCHA token.
  // Tries standard secret keys first, then Enterprise API.
  // Token passes if any method succeeds.
  async verify(token: string | undefined, remoteIp?: string): Promise<void> {
    // Skip verification in development if nothing is configured
    if (!this.hasAnyConfig) {
      this.logger.warn("No RECAPTCHA config found — skipping CAPTCHA verification.");
      return;
    }

    if (!token) {
      throw new HttpException(
        {
          statusCode: HttpStatus.UNPROCESSABLE_ENTITY,
          error: "CAPTCHA_TOKEN_MISSING",
          message: "CAPTCHA token is required.",
        },
        HttpStatus.UNPROCESSABLE_ENTITY,
      );
    }

    try {
      // ── Standard reCAPTCHA v2/v3 ───────────────────────────────────────────────
      for (const secret of this.secrets) {
        const params = new URLSearchParams({ secret, response: token });
        if (remoteIp) params.append("remoteip", remoteIp);

        const response = await this.fetchWithTimeout(
          "https://www.google.com/recaptcha/api/siteverify",
          {
            method: "POST",
            headers: { "Content-Type": "application/x-www-form-urlencoded" },
            body: params.toString(),
          },
        );

        const data = (await response.json()) as { success: boolean; "error-codes"?: string[] };
        if (data.success) return; // token is valid — done
        if (data["error-codes"]?.length) {
          this.logger.debug(`CAPTCHA standard rejected: ${data["error-codes"].join(", ")}`);
        }
      }

      // ── reCAPTCHA Enterprise (Android, Windows, …) ────────────────────────────
      // Try each registered Enterprise site key — the token was generated by one
      // of them but we don't know which, so we try all until one accepts it.
      if (this.enterpriseApiKey && this.enterpriseProjectId && this.enterpriseSiteKeys.length > 0) {
        const url = `https://recaptchaenterprise.googleapis.com/v1/projects/${this.enterpriseProjectId}/assessments?key=${this.enterpriseApiKey}`;

        for (const siteKey of this.enterpriseSiteKeys) {
          const response = await this.fetchWithTimeout(url, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              event: { token, siteKey },
            }),
          });

          const data = (await response.json()) as {
            tokenProperties?: { valid: boolean; invalidReason?: string };
            riskAnalysis?: { score: number };
          };

          if (data.tokenProperties?.valid) {
            const score = data.riskAnalysis?.score ?? 0;
            // Score 0.0 = likely bot, 1.0 = likely human. Threshold: 0.5
            if (score >= 0.5) return;
            this.logger.debug(`CAPTCHA Enterprise (${siteKey.substring(0, 8)}…): valid but score too low (${score})`);
          } else {
            this.logger.debug(`CAPTCHA Enterprise (${siteKey.substring(0, 8)}…): ${data.tokenProperties?.invalidReason ?? "rejected"}`);
          }
        }
      }

      // Nothing accepted the token
      throw new HttpException(
        {
          statusCode: HttpStatus.UNPROCESSABLE_ENTITY,
          error: "CAPTCHA_FAILED",
          message: "CAPTCHA verification failed. Please try again.",
        },
        HttpStatus.UNPROCESSABLE_ENTITY,
      );
    } catch (error) {
      // If it's already our HttpException, re-throw it
      if (error instanceof HttpException) throw error;

      this.logger.error("CAPTCHA verification request failed", error);
      throw new HttpException(
        {
          statusCode: HttpStatus.SERVICE_UNAVAILABLE,
          error: "CAPTCHA_UNAVAILABLE",
          message: "CAPTCHA service timed out or is temporarily unavailable. Please try again.",
        },
        HttpStatus.SERVICE_UNAVAILABLE,
      );
    }
  }

  private async fetchWithTimeout(input: string, init: RequestInit): Promise<Response> {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), RecaptchaService.VERIFY_TIMEOUT_MS);

    try {
      return await fetch(input, {
        ...init,
        signal: controller.signal,
      });
    } finally {
      clearTimeout(timeoutId);
    }
  }
}
