import { IsIn, IsNotEmpty, IsOptional, IsString, MaxLength } from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

/**
 * OAuth2 Authorization Request DTO (RFC 6749)
 * GET /api/v1/oauth/authorize query parameters
 */
export class AuthorizeDto {
  /**
   * Client identifier issued to the client during registration.
   */
  @ApiProperty({ example: 'client_abc123', description: 'Client identifier issued during registration' })
  @IsString()
  @IsNotEmpty()
  @MaxLength(128)
  client_id!: string;

  /**
   * Redirect URI for authorization code response.
   * Must match exactly with registered redirect URI.
   * 2048 chars matches the limit used by most browsers for URL length.
   */
  @ApiProperty({ example: 'https://example.com/callback', description: 'Must match exactly the registered redirect URI' })
  @IsString()
  @IsNotEmpty()
  @MaxLength(2048)
  redirect_uri!: string;

  /**
   * Response type. MUST be "code" for authorization code flow.
   */
  @ApiProperty({ example: 'code', enum: ['code'], description: 'Must be "code" for authorization code flow' })
  @IsString()
  @IsNotEmpty()
  @IsIn(['code'])
  response_type!: 'code';

  /**
   * Space-separated list of scopes (e.g., "read write").
   * Limit to 256 chars - plenty of room for multiple scopes.
   */
  @ApiProperty({ example: 'read write', description: 'Space-separated list of requested scopes' })
  @IsString()
  @IsNotEmpty()
  @MaxLength(256)
  scope!: string;

  /**
   * Opaque state parameter to prevent CSRF.
   * The authorization server must include this unchanged in the redirect.
   */
  @ApiProperty({ example: 'random_csrf_state_token', description: 'CSRF protection token generated by client' })
  @IsString()
  @IsNotEmpty()
  @MaxLength(512)
  state!: string;

  /**
   * PKCE: Code challenge (base64-url-encoded SHA256 hash of code_verifier).
   * SHA256 output base64url-encoded is exactly 43 chars.
   */
  @ApiPropertyOptional({ example: 'E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM', description: 'PKCE: BASE64-URL(SHA256(code_verifier))' })
  @IsOptional()
  @IsString()
  @MaxLength(128)
  code_challenge?: string;

  /**
   * PKCE: Code challenge method. Must be "S256" if code_challenge provided.
   */
  @ApiPropertyOptional({ example: 'S256', enum: ['S256'], description: 'PKCE challenge method, must be "S256"' })
  @IsOptional()
  @IsString()
  @IsIn(['S256'])
  code_challenge_method?: 'S256';
}

/**
 * Authorization approval response structure.
 * Returned after user confirms permission to authorize the client.
 */
export class AuthorizeResponseDto {
  code!: string;
  state!: string;
}
